In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('SongsByGenre.csv')

In [3]:
df

id  \
0      7wj1Lb5ggzMWJ9TqZJ2dwo   
1      5SdG78xwNRsjXmFGhm9Z8D   
2      49T9pCYlpvtGd9ugZt7DSZ   
3      0TJWjCuRZLRrBSZLBIF7EW   
4      1EAgPzRbK9YmdOESSMUm6P   
...                       ...   
10777  1p4q4NrA1943aFMuXrPFET   
10778  7MFsLdEb5V395J9Zsy9xls   
10779  1rsWv1SDZm7i1Y9CRU0LHt   
10780  3IlcdbAbQnUK29ukzKczfu   
10781  7rRtZJhhWRcu2hCgokAPPV   

                                                    name  popularity  \
0                                                     Up          54   
1                                  Om du letar efter nån          36   
2                                             If I Could          53   
3                                                     Up          45   
4                                                   Home          55   
...                                                  ...         ...   
10777                                          Stonegoat           4   
10778                               Cancion Del Mariachi          50   
10779                                          Ez Keç Im          35   
10780  Swara-Kakali (based on Raga Tilang) - 1999 Rem...          13   
10781                                  Hijack The Barber           6   

                                                   genre  \
0                                               acoustic   
1                      acoustic;acoustic;swedish;swedish   
2                          acoustic;acoustic;chill;chill   
3                                               acoustic   
4      acoustic;acoustic;acoustic;road-trip;road-trip...   
...                                                  ...   
10777                                        world-music   
10778                                        world-music   
10779                                        world-music   
10780                                        world-music   
10781                                        world-music   

                                            album  \
0                                    My World 2.0   
1                             Innan jag kände dig   
2                               In Between Dreams   
3                                   The Awakening   
4             The World From The Side Of The Moon   
...                                           ...   
10777                   Stonegoat / Dreambuilding   
10778                        Mexico and Mariachis   
10779                                       Nûpel   
10780               The Very Best of Ravi Shankar   
10781  Sound System FM: Reggae & Roots In Session   

                           artists  key  mode  time_signature  acousticness  \
0                    Justin Bieber    0     1               4        0.0840   
1                     Melissa Horn   10     1               4        0.8100   
2                     Jack Johnson    9     1               4        0.7620   
3          James Morrison;Jessie J   11     0               4        0.4250   
4                 Phillip Phillips    0     1               4        0.0256   
...                            ...  ...   ...             ...           ...   
10777                         Goat    2     1               3        0.0299   
10778   Antonio Banderas/los Lobos    4     0               4        0.5510   
10779                        Aynur    2     0               4        0.4940   
10780  Ravi Shankar;Yehudi Menuhin    1     1               4        0.7220   
10781                   King Tubby    1     0               4        0.0153   

       danceability  energy  instrumentalness  liveness  loudness  \
0             0.711   0.717          0.000000    0.0900    -4.317   
1             0.556   0.284          0.000095    0.1870   -15.177   
2             0.714   0.321          0.385000    0.0993   -14.517   
3             0.437   0.632          0.000000    0.4450    -6.781   
4             0.606   0.826          0.000016    0.1170    -6.040   
...             ...     ...               ..

In [4]:
from sklearn.metrics.pairwise import sigmoid_kernel

In [5]:
da = df

In [6]:
dfno = da.drop(['id', 'name', 'genre', 'album', 'artists', 'mode', 'time_signature', 'duration_ms', 'lyrics', 'popularity', 'key'], 1)

In [7]:
from sklearn import preprocessing
dfnor  = preprocessing.normalize(dfno)

In [8]:
dfnor

array([[6.66516169e-04, 5.64158329e-03, 5.68919158e-03, ...,
        3.14214765e-04, 4.67354790e-03, 9.99369583e-01],
       [6.18804056e-03, 4.24759327e-03, 2.16963397e-03, ...,
        2.30714599e-04, 5.02682801e-03, 9.93211068e-01],
       [6.61724647e-03, 6.20041204e-03, 2.78758020e-03, ...,
        3.71677361e-04, 4.14229208e-03, 9.91961718e-01],
       ...,
       [3.95071100e-03, 5.59817348e-03, 6.70181339e-03, ...,
        4.76644485e-04, 7.65350289e-03, 9.98490222e-01],
       [4.91284946e-03, 3.17770180e-03, 3.78330235e-03, ...,
        4.14394089e-04, 3.72206185e-03, 9.95893104e-01],
       [1.90489570e-04, 9.07626773e-03, 5.46568112e-03, ...,
        5.00502007e-04, 3.74753990e-03, 9.91927745e-01]])

In [10]:
sig[1000]

array([0.80445372, 0.80431686, 0.80428115, ..., 0.80444533, 0.80438872,
       0.80428152])

In [11]:
sig[100]

array([0.80414916, 0.80441649, 0.80443272, ..., 0.80423684, 0.80436131,
       0.8044317 ])

In [12]:
sig[0]

array([0.8044548 , 0.80432231, 0.80428733, ..., 0.80444709, 0.80439246,
       0.80428681])

In [13]:
names = pd.Series(df.index, index=df['name'])

In [14]:
names

name
Up                                                                   0
Om du letar efter nån                                                1
If I Could                                                           2
Up                                                                   3
Home                                                                 4
                                                                 ...  
Stonegoat                                                        10777
Cancion Del Mariachi                                             10778
Ez Keç Im                                                        10779
Swara-Kakali (based on Raga Tilang) - 1999 Remastered Version    10780
Hijack The Barber                                                10781
Length: 10782, dtype: int64

In [15]:
sig = sigmoid_kernel(dfnor, dfnor)
def recommend(name, sig=sig):
    index = names[name]
    sScore = list(enumerate(sig[index]))
    sScore = sorted(sScore, key=lambda x: x[1], reverse=True)
    sScore = sScore[0:11]
    songIndex = [i[0] for i in sScore]
    return df['name'].iloc[songIndex]

In [16]:
recommend('Baby')

88                           Baby
3077           Nightshift In Blue
2123                     Don Dada
8611             Rastafari Anthem
5216                Mr. Lova Lova
3850           Love You That Much
7084                      Som Mil
5762     いつもそばにいるよ / Stand by You
12                          Drive
4840    Don't Sweat The Technique
4439                   Tom Sawyer
Name: name, dtype: object

In [17]:
recommend('Set Fire to the Rain')

9108                           Set Fire to the Rain
10395    When Love Takes Over (feat. Kelly Rowland)
9639                                   Falling Down
5935                                   WAY OF GLORY
144                                   We Found Love
513                                      世界は恋に落ちている
5690       I Got a Feeling (feat. Benjamin Diamond)
1535                                  Glad You Came
3210                                          Space
3122            Fade Into Darkness - Vocal Club Mix
5801                                          irony
Name: name, dtype: object

In [18]:
recommend('I Remember - Radio Edit')

10530                              I Remember - Radio Edit
10601                                       Feel Good Inc.
851      Running On Faith - Acoustic; Live at MTV Unplu...
6332                                          So Long Song
1493                                       I Gotta Feeling
2908                                      Freaks Orchestra
5048                                   Apollo - Radio Edit
1495                                     Heart Of The Band
10052                     La Niña Que Llora en Tus Fiestas
1271                                      The Hardest Part
4817                                       Back in the Day
Name: name, dtype: object

In [19]:
sorted(list(enumerate(sig[names['I Gotta Feeling']])), key=lambda x: x[1], reverse=True)

[(1493, 0.8044548002984013),
 (5901, 0.8044547725315284),
 (3502, 0.8044547226489809),
 (4985, 0.8044547223593284),
 (1238, 0.804454705320979),
 (2031, 0.8044547050618487),
 (5481, 0.804454698698746),
 (9267, 0.8044546954486391),
 (3846, 0.8044546945005938),
 (9355, 0.804454693558489),
 (4318, 0.80445469291003),
 (1570, 0.8044546896012856),
 (10601, 0.8044546868105064),
 (7259, 0.8044546801102735),
 (10238, 0.8044546800322696),
 (3659, 0.8044546795322306),
 (6718, 0.8044546746501904),
 (3078, 0.8044546732695549),
 (7789, 0.804454666629809),
 (4247, 0.8044546660693728),
 (2908, 0.8044546610978125),
 (10530, 0.8044546587708733),
 (6486, 0.8044546585672131),
 (8890, 0.8044546550977445),
 (1762, 0.8044546494909448),
 (10664, 0.8044546475896543),
 (10352, 0.8044546474755028),
 (10730, 0.8044546435288042),
 (7092, 0.8044546291599562),
 (4151, 0.8044546259194204),
 (10148, 0.8044546250867302),
 (1108, 0.8044546215256703),
 (10516, 0.8044546191916406),
 (9440, 0.8044546189387414),
 (1819, 0.80

In [20]:
sorted(list(enumerate(sig[names['Baby']])), key=lambda x: x[1], reverse=True)

[(88, 0.8044548002984013),
 (3077, 0.8044545191759959),
 (2123, 0.804454195937335),
 (8611, 0.8044541059003383),
 (5216, 0.804454103039522),
 (3850, 0.8044540997087555),
 (7084, 0.8044540330766612),
 (5762, 0.8044540138976581),
 (12, 0.8044540096821251),
 (4840, 0.8044539553830338),
 (4439, 0.804453925357417),
 (5667, 0.8044538994486198),
 (2154, 0.8044538942983472),
 (7857, 0.8044538463689297),
 (9875, 0.8044538332328244),
 (7867, 0.8044538246555119),
 (3225, 0.8044538237580106),
 (6545, 0.8044538107429189),
 (9288, 0.8044537978879185),
 (10650, 0.8044537960322631),
 (2164, 0.8044537678497544),
 (8566, 0.8044537657013956),
 (2507, 0.8044537626902448),
 (4764, 0.8044537536265706),
 (7590, 0.8044537429629774),
 (8612, 0.8044537381401083),
 (4785, 0.8044537238756541),
 (9293, 0.804453696566672),
 (5355, 0.8044536956064225),
 (1750, 0.8044536815351043),
 (4121, 0.804453669853395),
 (8743, 0.8044536477762758),
 (9202, 0.8044536401262559),
 (8772, 0.8044536332403163),
 (9601, 0.804453629550

In [21]:
sorted(list(enumerate(sig[names['Set Fire to the Rain']])), key=lambda x: x[1], reverse=True)

[(9108, 0.8044548002984013),
 (10395, 0.8044547832133244),
 (9639, 0.8044547830493679),
 (5935, 0.8044547781078446),
 (144, 0.8044547753431732),
 (513, 0.8044547710853864),
 (5690, 0.8044547702185447),
 (1535, 0.8044547689888188),
 (3210, 0.8044547615166475),
 (3122, 0.8044547610713915),
 (5801, 0.8044547550980045),
 (10713, 0.8044547540466009),
 (5386, 0.8044547538121533),
 (10434, 0.8044547499125322),
 (6500, 0.8044547488889856),
 (9785, 0.8044547487942492),
 (10093, 0.8044547485297037),
 (8863, 0.8044547480250642),
 (2961, 0.8044547446831932),
 (5879, 0.8044547325730137),
 (8044, 0.804454732017162),
 (9751, 0.8044547304752605),
 (6462, 0.8044547304592041),
 (2484, 0.8044547299371569),
 (1801, 0.8044547268355362),
 (290, 0.8044547267765714),
 (10408, 0.8044547261986592),
 (6050, 0.8044547254541976),
 (0, 0.8044547245820816),
 (7759, 0.8044547242276695),
 (3733, 0.8044547219311771),
 (7813, 0.8044547212814853),
 (7792, 0.8044547192310084),
 (143, 0.8044547172206857),
 (1487, 0.8044547

In [22]:
sorted(list(enumerate(sig[names['I Remember - Radio Edit']])), key=lambda x: x[1], reverse=True)

[(10530, 0.8044548002984013),
 (10601, 0.8044546844568298),
 (851, 0.8044546747124068),
 (6332, 0.8044546715898513),
 (1493, 0.8044546587708733),
 (2908, 0.804454657841514),
 (5048, 0.8044546284198615),
 (1495, 0.80445460696197),
 (10052, 0.8044545918888246),
 (1271, 0.8044545780611139),
 (4817, 0.8044545704749764),
 (10352, 0.8044545698823341),
 (3065, 0.8044545686946971),
 (4237, 0.8044545654161144),
 (7469, 0.8044545640965066),
 (1556, 0.8044545626455827),
 (3836, 0.8044545541616693),
 (6486, 0.8044545525550334),
 (1762, 0.8044545402941118),
 (5901, 0.804454532744733),
 (9355, 0.8044545279714365),
 (3720, 0.8044545259437693),
 (7947, 0.8044545186936274),
 (10238, 0.8044545012923963),
 (5425, 0.804454500498974),
 (8383, 0.8044544994831762),
 (3846, 0.8044544908705812),
 (747, 0.8044544855873393),
 (4985, 0.8044544818631545),
 (208, 0.8044544817683221),
 (4247, 0.8044544787976907),
 (4151, 0.804454477312512),
 (1108, 0.8044544644070091),
 (3813, 0.8044544610980334),
 (3078, 0.80445446

In [23]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(client_id="7f839484fcf4450db86dcc9126cec5e1",\
                                client_secret="80e9b5a936a44b2880354a719ef54019", requests_timeout = None))

In [24]:
gottaFeelingRec = recommend('I Gotta Feeling').tolist()

In [27]:
recommendedTracks = sp.recommendations(seed_tracks = [df['id'].iloc[names['I Gotta Feeling']]],country='CA',limit = 11)
spotifyRecList = []
for track in recommendedTracks['tracks']:
    spotifyRecList.append(track['name'])

In [28]:
gottaFeelingRec

['I Gotta Feeling',
 '6月の青い空',
 'Pompeii',
 'Young',
 'Parklife',
 'Falling - Psychemagik Remix',
 'Tomorrow Never Comes',
 'Saia Rendada',
 'Hear This',
 'A Vida é um Rodeio',
 'Sleepyhead']

In [29]:
spotifyRecList

['We R Who We R',
 'Valerie (feat. Amy Winehouse) - Version Revisited',
 'Teenage Dream',
 'Where Is The Love?',
 'Beautiful Girls',
 'Temperature',
 'Break Your Heart',
 'TiK ToK',
 'Wild Ones (feat. Sia)',
 'Party Rock Anthem',
 'Rock DJ']

In [31]:
from sklearn.metrics import accuracy_score
accuracy_score(spotifyRecList, gottaFeelingRec)

0.0